### PR TITLE
Solutions to selected problems of CH3

### PR DESCRIPTION
**Pull request by ikarosilva**
Solutions to selected problems of CH3  at the bottom of the notebook (top of the notebook are the codes from the original chapter, which contains some snippets useful to solving the solutions at the bottom). 

Problem 3H17 is incomplete but left for reference in case  it maybe of help to others (feel free to delete if you want to keep full solutions only).

### CODE REVIEW

**Comment by canyon289** [comment]
This is amazing. Thank you so much.

Would you mind if I added markdown headers and moved the solutions to this repo so folks can more easily find them?
https://github.com/BayesianModelingandComputationInPython/BMCPSolutions_Edition1/tree/main/notebooks

**Comment by ikarosilva** [comment]
Yes, please do (that is why I wanted to share :)). Sorry I did not clean the markdowns.

**Comment by ikarosilva** [comment]
Added selected solutions to Chapter 4. Could not do the last problem because the "gravity_measurements.csv" file is missing from the repo.

**Comment by canyon289** [comment]
Ill merge this as is so folks can see it! Thank you so much

**Pull request merged**
